(library
 (name stm_volatile)
 (modules stm_volatile))

(library
 (name stm_snapshot)
 (modules stm_snapshot)
 (libraries stm_volatile))

(executable
 (name qcheck_stm_volatile)
 (modules qcheck_stm_volatile)
 (libraries stm_volatile qcheck-stm.sequential qcheck-stm.domain qcheck-core))

(executable
 (name qcheck_stm_snapshot)
 (modules qcheck_stm_snapshot)
 (libraries stm_snapshot qcheck-stm.sequential qcheck-stm.domain qcheck-core))
